### ISSUE TITLE
Allow deletion of Current Vaccine only

### ISSUE THREAD

**Issue by NaveedAhmadHematmal** [VDTS/CodeX.VaxineSolution#34]

**Comment by SaeedaRasuly** [comment]
Can you elaborate it? Mean of allowing deletion of current vaccine only

**Comment by NaveedAhmadHematmal** [comment]
@SaeedaRasuly There is a timeline of vaccines for every child on the Home page. You can add one vaccine per month, and can only delete or edit the vaccine in the vaccine period (Vaccine Month), and you are not allowed to edit or delete vaccines of months before this because they are already reported to the office and actually no need to edit or delete them.

**Comment by NaveedAhmadHematmal** [comment]
@SaeedaRasuly If you have another idea, don't hesitate to share.

**Comment by SaeedaRasuly** [comment]
Noted, thanks

**Comment by NaveedAhmadHematmal** [comment]
We need to add the vaccine periods (Vaccine months) page on the admin website, and the admin can add vaccine periods. 
mobilizers are allowed to add vaccines during that period.
