### ISSUE TITLE
Edited Child DOB bug

### ISSUE THREAD

**Issue by NaveedAhmadHematmal** [VDTS/CodeX.VaxineSolution#65]
Editing a child changes the DateTime format and causes crashes while adding a vaccine to this child.

**Comment by NaveedAhmadHematmal** [comment]
The same bug is in Edited Family and Vaccine

**Comment by SaeedaRasuly** [comment]
How? Editing a child changes dateTime format???

**Comment by NaveedAhmadHematmal** [comment]
We are using UTC time format in our view models but in edit pages view models it is Local time format.
